# Attempt to load a config.make file.
# If none is found, project defaults in config.project.make will be used.
#ifneq ($(wildcard config.make),)
#	include config.make
#endif

# make sure the the SDLGUI_ROOT location is defined
ifndef SDLGUI_ROOT
    SDLGUI_ROOT =$(realpath ../../..)
endif

# call the project makefile!
#include compile.project.mk
